// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
      ? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<TRelationship["fields"][number], string>]: TFieldKey extends keyof TData
      ? TData[TFieldKey]
      : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<TCustomType[number], string>["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Coupons → Offers*
 */
export interface CouponsDocumentDataOffersItem {
  /**
   * Offer Image field in *Coupons → Offers*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: coupons.offers[].offer_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  offer_image: prismic.ImageField<never>;

  /**
   * Badge Label field in *Coupons → Offers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coupons.offers[].badge_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  badge_label: prismic.KeyTextField;

  /**
   * Icon field in *Coupons → Offers*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: coupons.offers[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Offer Title field in *Coupons → Offers*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coupons.offers[].offer_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  offer_title: prismic.RichTextField;

  /**
   * Offer Subtitle field in *Coupons → Offers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coupons.offers[].offer_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  offer_subtitle: prismic.KeyTextField;

  /**
   * Offer Description field in *Coupons → Offers*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coupons.offers[].offer_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  offer_description: prismic.RichTextField;

  /**
   * Promo Code field in *Coupons → Offers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coupons.offers[].promo_code
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  promo_code: prismic.KeyTextField;
}

type CouponsDocumentDataSlicesSlice = never;

/**
 * Content for Coupons documents
 */
interface CouponsDocumentData {
  /**
   * Carousel Title field in *Coupons*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coupons.carousel_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  carousel_title: prismic.RichTextField;

  /**
   * Offers field in *Coupons*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: coupons.offers[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  offers: prismic.GroupField<Simplify<CouponsDocumentDataOffersItem>>;

  /**
   * View All Button field in *Coupons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: coupons.view_all_button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  view_all_button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Slice Zone field in *Coupons*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: coupons.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<CouponsDocumentDataSlicesSlice>;
}

/**
 * Coupons document from Prismic
 *
 * - **API ID**: `coupons`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CouponsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<CouponsDocumentData>,
  "coupons",
  Lang
>;

/**
 * Item in *Home Hero → Images*
 */
export interface HomeHeroDocumentDataImagesItem {
  /**
   * Image field in *Home Hero → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Home Hero → Links*
 */
export interface HomeHeroDocumentDataLinksItem {
  /**
   * Link field in *Home Hero → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Icon field in *Home Hero → Links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.links[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Content for Home Hero documents
 */
interface HomeHeroDocumentData {
  /**
   * Heading field in *Home Hero*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Images field in *Home Hero*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  images: prismic.GroupField<Simplify<HomeHeroDocumentDataImagesItem>>;

  /**
   * Links field in *Home Hero*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links: prismic.GroupField<Simplify<HomeHeroDocumentDataLinksItem>>;
}

/**
 * Home Hero document from Prismic
 *
 * - **API ID**: `home_hero`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeHeroDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<HomeHeroDocumentData>,
  "home_hero",
  Lang
>;

export type AllDocumentTypes = CouponsDocument | HomeHeroDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CouponsDocument,
      CouponsDocumentData,
      CouponsDocumentDataOffersItem,
      CouponsDocumentDataSlicesSlice,
      HomeHeroDocument,
      HomeHeroDocumentData,
      HomeHeroDocumentDataImagesItem,
      HomeHeroDocumentDataLinksItem,
      AllDocumentTypes,
    };
  }
}
